--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Sandertv/BlockPets
branches:
- master
projects:
  BlockPets:
    path: ""
    icon: resources/BlockPetsLogo.png
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0
      - src: poggit/libasynql/libasynql
        version: ^3.0
      - src: muqsit/InvMenu/InvMenu
        version: ^1.1.1
...
